name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linter
        run: |
          echo "Running flake8 on Python files..."
          # Only run if files exist
          if find . -name "*.py" | grep .; then
            find . -name "*.py" -exec flake8 {} +
            echo "✅ Python linting complete."
          else
            echo "⚠️ No Python files found to lint."
          fi

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run Linter
        run: |
          echo "Running jshint on JavaScript files..."
          if find ./server/database -name "*.js" | grep .; then
            find ./server/database -name "*.js" -exec jshint {} +
            echo "✅ JavaScript linting complete."
          else
            echo "⚠️ No JavaScript files found to lint."
          fi
